### ISSUE TITLE
Where is the models code?

### ISSUE THREAD

**Issue by Kaimary** [mnschmit/unsupervised-graph-text-conversion#2]
@mnschmit Sorry but I can’t find the models code in the branch. Do I miss something?

**Comment by Kaimary** [comment]
I mean the below package,
-- include-package src.models.copynet_shared_decoder
And looks like the interleaving type datasetreader is missing as well?

**Comment by mnschmit** [comment]
Hi @Kaimary ! Thanks for noticing. It was indeed a problem with the gitignore. So the model code was excluded. Now everything should be there.

The class `InterleavingDatasetReader` is provided by AllenNLP. It is registered as "interleaving". So it should be found when AllenNLP is correctly installed.
