### ISSUE TITLE
Noise function `blank` is not applied to graphs

### ISSUE THREAD

**Issue by alxthm** [mnschmit/unsupervised-graph-text-conversion#3]
Hi, thanks for making your code available and easy to read!

It seems to me that the `blank_elem` function does not add noise to the graphs, since variable `blanked_facts` is not actually used?
https://github.com/mnschmit/unsupervised-graph-text-conversion/blob/5d915a40e6d58a9aeabaa9d52ce074385e5f6db1/src/features/make_noise.py#L92
I imagine the line
```
    return fact_delim.join([elem_delim.join(f) for f in facts])
```
should be replaced by
```
    return fact_delim.join([elem_delim.join(f) for f in blanked_facts])
```

If this is the case however, I understand that this function would replace some elements in the facts of the graph by the blank token (e.g. `pants SEP attr SEP white EOF pants SEP playing SEP tennis` -> `pants SEP attr SEP blanked EOF pants SEP blanked SEP tennis`).
But in the paper, you mention replacing entire facts by the blank token (e.g. `pants SEP attr SEP white EOF pants SEP playing SEP tennis` -> `pants SEP attr SEP white EOF blanked`). Is that correct ?

**Comment by mnschmit** [comment]
Hi @alexandrethm 
thank you for bringing this to my attention!
You are right. There is an error in the code. It only applies the identity function on graphs when calling `blank`.

 The `blank_elem` (after your fix) is a variant that is also worth looking into as a source of noise but the paper indeed describes _blank_ as blanking out entire facts. I will fix this immediately.
